#!/bin/bash

# Returns a # if received 1 and returns nothing if received 0

# Capture the command and its arguments
command="$1"
shift  # Remove the first argument (command) from the list
args=("$@")

# Execute the command
"$command" "${args[@]}"


if [ $? -eq 0 ]
then
  echo ""
else
  echo "#"
fi
