#!bin/bash

# Compare two version numbers

mode=$1


# Compares version A to version B and if A is greater than or equal to B returns 0, otherwise returns 1
function version-gte {
  local version=$($1 --version | grep -oP "(?<=\bversion\s)\S+")
  if [ $version == $2 ]
  then
    return 0
  fi
  if [[ $(printf "%s\n" "$version" $2 | sort -V | head -n 1) != "$version" ]]
  then
      return 1
  fi
  return 0
}

# Compares version A to version B and if A is greater than B returns 0, otherwise returns 1
function version-gt {
  local version=$($1 --version | grep -oP "(?<=\bversion\s)\S+")
  if [[ $(printf "%s\n" "$version" $2 | sort -V | head -n 1) != "$version" ]]
  then
      return 1
  fi
  return 0
}

# Compares version A to version B and if A is less than or equal to B returns 0, otherwise returns 1
function version-lse {
  return ! version-gte
}

# Compares version A to version B and if A is less than B returns 0, otherwise returns 1
function version-ls {
  return ! version-gt
}



